# Generated by Django 5.0 on 2024-08-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='coin_count',
            new_name='essence_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coin_message',
        ),
    ]
