# Generated by Django 5.0 on 2024-08-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_essence_count_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='essence_count',
            field=models.IntegerField(default=0),
        ),
    ]
