# Generated by Django 5.0 on 2024-08-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_essence_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
