# Generated by Django 5.0 on 2024-08-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='name',
            new_name='bundle_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='character_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='profile_name',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='name',
            new_name='set_name',
        ),
    ]
