# Generated by Django 5.0.1 on 2024-09-01 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_item_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inventory',
        ),
        migrations.CreateModel(
            name='ProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_items', to='main.item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_items', to='main.profile')),
            ],
            options={
                'unique_together': {('profile', 'item')},
            },
        ),
    ]
