# Generated by Django 5.0.1 on 2024-09-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_end_date_event_date_remove_event_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.AddField(
            model_name='seasonalcontent',
            name='sc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sc_photos/'),
        ),
    ]
